### ISSUE TITLE
Game softlocks after landing on a battle space

### ISSUE THREAD

**Issue by Rancma987** [Rainchus/Mp3-Combination#5]
Played on Project64. Didn't touch the minigame list, went strait to MP3 by pressing A when booting the game.

After landing on a battle space (if the battle isn't for 0 coins), the roulette doesn't show up when it's supposed to. Instead the game stays on the screen right before that.

Tested this multiple times on Chilly Waters, it happened every time.

**Comment by Rainchus** [comment]
When doing this, did you use an existing save or create a new one?

**Comment by Rancma987** [comment]
I had an existing save file. I tried playing this with Project64-MPN (this is a custom Project64 for Mario Party Netplay, it identifies the combinaison rom as MP3 and gives you a 100% save file when starting the game)

**Comment by Rainchus** [comment]
I believe the problem was related to the custom save data and how it initializes. If no minigames are selected for a category, it will softlock trying to find valid minigames in a list that is empty. Can you try [this](https://github.com/Rainchus/Mp3-Combination/releases/tag/v0.1.6) version and let me know if it still occurs?

**Comment by Rancma987** [comment]
The custom save actually messes up with the minigame list. About half of the minigames were toggled off so that's where the issue came from.

I didn't have any issues with the newer version. Thank you for your support and keep up the good work!
